apiVersion: apps/v1
kind: Deployment
metadata:
  name: filevault-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: filevault
  template:
    metadata:
      labels:
        app: filevault
    spec:
      containers:
      - name: filevault-container
        image: filevaultacr.azurecr.io/filevault:v1
        ports:
        - containerPort: 3000
          name: web
        resources:
          requests:
            cpu: 10m
            memory: 128Mi
          limits:
            cpu: 250m
            memory: 256Mi
