filebeat.inputs:
# - type: log
#   enabled: true
#   paths:
#     - /var/lib/docker/containers/*/*.log
#     - /usr/share/filebeat/ingest_data/nginx/access.json
#     - /usr/share/filebeat/ingest_data/nginx/error.log
#   json.keys_under_root: true
#   json.add_error_key: true
- type: filestream
  id: default-filestream
  paths:
    - /usr/share/filebeat/ingest_data/nginx/*
    # - /usr/share/filebeat/ingest_data/nginx/access.json
    # - ingest_data/nginx/access.json
    # - ingest_data/*.log

processors:
  - add_docker_metadata:
      host: "unix:///var/run/docker.sock"

output.logstash:
  hosts: ${LOGSTASH_HOSTS}