logging.to_files: false
logging.to_stderr: true
logging.level: debug

filebeat.inputs:
- type: filestream
  enabled: true
  id: default-filestream
  take_over: true
  paths:
    - /usr/share/filebeat/ingest_data/nginx/access.json
  parsers:
    - ndjson:
        keys_under_root: true

processors:
  - add_docker_metadata:
      host: "unix:///var/run/docker.sock"

output.logstash:
  hosts: ${LOGSTASH_HOSTS}
