global:
  scrape_interval: 15s
  evaluation_interval: 15s


scrape_configs:
  - job_name: 'node'
    static_configs:
      - targets: ['node-exporter:9100']
    scrape_interval: 5s

  - job_name: 'filevault'
    static_configs:
      - targets: ['web:3000']
    scrape_interval: 5s
      

remote_write:
  - url: "${PROMETHEUS_URL}"
    basic_auth:
      username: "${PROMETHEUS_USERNAME}"
      password: "${PROMETHEUS_PASSWORD}"
