apiVersion: v1
kind: Service
metadata:
  name: filevault-service
spec:
  selector:
    app: filevault
  ports:
  - name: filevault-port
    protocol: TCP
    port: 3000
    targetPort: web
  type: LoadBalancer
