# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - filevault-webapp

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  build:
    runs-on: 'ubuntu-latest'
    environment:
      name: 'production'

    steps:
    - uses: actions/checkout@v2

    - name: Azure login
      uses: azure/login@v2
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    - name: Create .env file
      run: |
        touch ./src/azure-sa/.env
        echo AZURE_STORAGE_ACCOUNT_NAME=${{ secrets.AZURE_STORAGE_ACCOUNT_NAME }} >> ./src/azure-sa/.env
        echo AZURE_STORAGE_ACCOUNT_KEY=${{ secrets.AZURE_STORAGE_ACCOUNT_KEY }} >> ./src/azure-sa/.env
        echo AZURE_CONTAINER_NAME=${{ secrets.AZURE_CONTAINER_NAME }} >> ./src/azure-sa/.env
        echo PORT=${{ secrets.PORT }} >> ./src/azure-sa/.env

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://filevaultacr.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_46abcba7c2db48fb88fac9c831dae229 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_1537530cfbc04649ad741880711c84d2 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: filevaultacr.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_46abcba7c2db48fb88fac9c831dae229 }}/filevault:${{ github.sha }}
        context: ./src/azure-sa
        file: ./src/azure-sa/Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'filevault-webapp'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_884f40de5aa84c59b5ab7ef78ce9eadb }}
        images: 'filevaultacr.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_46abcba7c2db48fb88fac9c831dae229 }}/filevault:${{ github.sha }}'
